### ISSUE TITLE
The "remove team" button doesn't seem to do anything

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/hackathon-leaderboard#18]
I am unable to "remove team" -  the button doesn't seem to do anything.

<img width="1153" alt="jamstack_hackathon_2018___freecodecamp_org" src="https://user-images.githubusercontent.com/985197/47947830-9397b100-dee1-11e8-9ae4-c634c0dddf38.png">

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson, I noticed this, too. It seems to work fine if you refresh the page, but there should probably be a redirect here.
