### ISSUE TITLE
Server: Team sites must have a relevant lighthouse score attached

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/hackathon-leaderboard#2]
Site urls should be run against something like the [lighthouse](https://www.npmjs.com/package/lighthouse) module and scores added to the teams record in the database

**Comment by scissorsneedfoodtoo** [comment]
@Bouncey, by database, are we talking about the config.yaml files mentioned in #1? Or are you thinking of something more like Mongo?

**Comment by Bouncey** [comment]
More like mongo

**Comment by Bouncey** [comment]
Closed via #17
