### ISSUE TITLE
Can't edit existing hackathon team (results in "bad request" error)

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/hackathon-leaderboard#20]

**Comment by Bouncey** [comment]
My guess is this is related to #29

**Comment by tbushman** [comment]
Yes. #29 and #28 ... it's on the client side. @scissorsneedfoodtoo and I are looking into it.

**Comment by scissorsneedfoodtoo** [comment]
@tbushman, @Bouncey, I think I figured this out. Will make a comment over on #27.

**Comment by Bouncey** [comment]
Closed via #27
