### ISSUE TITLE
Server: Listen for webhooks and update a correct team record

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/hackathon-leaderboard#3]
- Webhook pings from GitHub will amend, where required, the team details in the database so they reflect the `config.yml` in the teams project route
- Webhook pings from Netlify will run the teams URL through the lighthouse tests and amend the teams record accordingly.
- (Time permitting) Webhook pings from Netlify could set a build status to pending, this status would only be consumed by the leaderboard

**Comment by scissorsneedfoodtoo** [comment]
@Bouncey, do you have a server boilerplate in mind? Or are you thinking of doing something from scratch, maybe with Express?

**Comment by Bouncey** [comment]
I was looking into using [Loopback 4](https://v4.loopback.io/) which is built using typeScript and is something we are looking to convert our production server too.

But I think it would be more sane to use express for this due to the time restraints

**Comment by Bouncey** [comment]
closed via #17
