### ISSUE TITLE
Simplify the Lighthouse column

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/hackathon-leaderboard#47]
For the lighthouse column all we need is the scores like this:

Speed: 100
SEO: 100

etc.

The entire thing could be a link you could click to see the full report (if a full report is available)

**Comment by tbushman** [comment]
@QuincyLarson I think we will have to build a view for results history because all we get back from the lighthouse api are these metrics, but we are storing all polled results for each team and we have discussed longitudinal visualization.

**Comment by QuincyLarson** [comment]
@tbushman I think this now looks much better thanks to yours and @raisedadead's PRs! Thanks again!
